development:
  adapter: mysql2
  database: erlt_development
  pool: 5
  timeout: 5000
  username: root
  password: 

production:
  adapter: mysql2
  database: erlt_production
  pool: 5
  timeout: 5000
  username: root
  password:

test:
  adapter: mysql2
  database: erl_test
  pool: 5
  timeout: 5000
  username: root
  password: 
